# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Dir - Demo

description: |
  This workflow demonstrates how to use the Dir CLI with a Kind cluster and Helm chart.
  It can be run in either local mode or network mode.
  It includes steps for building, pushing, publishing, listing and pulling agents.

on:
  workflow_dispatch:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Taskfile
        shell: bash
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Compile Dir CLI
        run: |
          echo "Compiling Dir CLI"
          task cli:compile
          echo "Dir CLI compiled successfully"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.2

      - name: Write Cosign private key
        run: |
          echo "Writing Cosign private and public keys"
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
          echo "${{ secrets.COSIGN_PUBLIC_KEY }}" > cosign.pub
          chmod 600 cosign.key
          chmod 644 cosign.pub
          echo "Cosign private and public keys written successfully"

      - name: Run build command
        run: |
          echo "Running dir build command"
          bin/dirctl build e2e/testdata > agent.json
          echo "Built agent.json:"
          cat agent.json

      - name: Run sign command
        run: |
          echo "Running dir sign command"
          bin/dirctl sign agent.json --key cosign.key --stdin > signed.model.json
          echo "Signed agent.json to signed.model.json"
          cat signed.model.json
          mv signed.model.json agent.json

      - name: Run verify command
        run: |
          echo "Running dir verify command"
          bin/dirctl verify agent.json --key cosign.pub
