# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Demo

description: |
  This workflow demonstrates how to use the Dir CLI with a Kind cluster and Helm chart.
  It includes steps for building, pushing, publishing, and listing images.

on:
  workflow_dispatch:
    inputs:
      dir-apiserver-image:
        required: true
        type: string
        default: "ghcr.io/agntcy/dir-apiserver"
      dir-helm-chart:
        required: true
        type: string
        default: "oci://ghcr.io/agntcy/dir/helm-charts/dir"
      dir-version:
        required: true
        type: string
        default: "v0.2.0"
      network:
        required: true
        type: boolean
        default: false

jobs:
  demo:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Taskfile
        run: |
          curl -L -o task.exe https://github.com/go-task/task/releases/latest/download/task_windows_amd64.exe
          move task.exe C:\tools\task.exe
          set PATH=C:\tools;%PATH%

      - name: Verify Taskfile Installation
        run: |
          task --version

      - name: Compile
        run: |
          echo "Compiling CLI"
          echo "Architecture: $(uname -m)"
          echo "OS: $(uname -s)"
          task cli:compile

      - name: Run version command on windows
        shell: bash
        run: |
          echo "Running version command"
          ./bin/dir version
